[package]
name = "jukebox"
version = "0.1.0"
description = "jukebox"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.12.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
lofty = "0.19.2"                                    # for reading audio tags
rodio = "0.18.0"                                    # for playing audio files
anyhow = "1.0.0"
figment = { version = "0.10", features = ["toml"] }
toml = "0.8.12"
