[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.2", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
lofty = "0.19.2"                                    # for reading audio tags
rodio = "0.18.0"                                    # for playing audio files
anyhow = "1.0"
figment = { version = "0.10", features = ["toml"] }
toml = "0.8.12"
cushy = "0.3.0"
state = "0.6.0"
