[package]
name = "jukebox"
version = "0.1.0"
description = "jukebox"
authors = ["Josh Clemens (clemensjosh@proton.me)"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.78"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.12.1", features = ["image", "svg"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
lofty = "0.20.0"
rodio = "0.19.0"
anyhow = "1.0.0"
figment = { version = "0.10", features = ["toml"] }
toml = "0.8.12"
walkdir = "2.5.0"
