[package]
name = "workspace"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui.workspace = true
ui.workspace = true
anyhow.workspace = true
schemars = "0"
parking_lot = "0"
serde.workspace = true
smallvec = "1.13.2"

[target.'cfg(target_os = "windows")'.dependencies]
windows.workspace = true
